In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read in data
baseball_df = pd.read_csv('Data/Statcast/Statcast_2020.csv')

In [3]:
baseball_df.head(10)

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
0,691,FF,2020-09-29,98.8,-0.41,6.46,"Fairbanks, Pete",605412,664126,field_out,...,3,1,3,1,3,Strategic,Standard,198.0,0.034,-0.370
1,709,FF,2020-09-29,98.7,-0.33,6.62,"Fairbanks, Pete",605412,664126,NaN,...,3,1,3,1,3,Strategic,Standard,189.0,0.003,0.040
2,720,SL,2020-09-29,89.6,-0.10,6.79,"Fairbanks, Pete",606192,664126,strikeout,...,3,1,3,1,3,Infield shift,Standard,58.0,0.053,-0.392
3,745,FF,2020-09-29,100.4,-0.38,6.50,"Fairbanks, Pete",606192,664126,NaN,...,3,1,3,1,3,Infield shift,Standard,191.0,0.000,-0.102
4,760,FF,2020-09-29,97.6,-0.18,6.63,"Fairbanks, Pete",606192,664126,NaN,...,3,1,3,1,3,Infield shift,Standard,191.0,0.000,-0.053
5,792,FF,2020-09-29,98.8,-0.31,6.67,"Fairbanks, Pete",606192,664126,NaN,...,3,1,3,1,3,Infield shift,Standard,198.0,0.000,0.103
6,820,FF,2020-09-29,99.1,-0.29,6.58,"Fairbanks, Pete",606192,664126,NaN,...,3,1,3,1,3,Infield shift,Standard,192.0,0.000,0.052
7,840,SL,2020-09-29,89.8,-0.20,6.74,"Fairbanks, Pete",606192,664126,NaN,...,3,1,3,1,3,Infield shift,Standard,67.0,0.000,0.019
8,870,SL,2020-09-29,86.7,-0.15,6.77,"Fairbanks, Pete",666971,664126,double,...,3,1,3,1,3,Standard,Standard,55.0,-0.056,0.433
9,898,SL,2020-09-29,86.8,-0.19,6.70,"Fairbanks, Pete",666971,664126,NaN,...,3,1,3,1,3,Standard,Standard,47.0,0.000,-0.033

In [5]:
# Save necessary columns to new df
pitch_df = baseball_df[['type', 'pitch_type', 'release_speed', 'effective_speed', 'release_spin_rate', 'release_pos_x', 'release_pos_z', 'zone', 'stand', 'p_throws', 'pitch_number']]

In [6]:
# Check new df
pitch_df.head(10)

,type,pitch_type,release_speed,effective_speed,release_spin_rate,release_pos_x,release_pos_z,zone,stand,p_throws,pitch_number
0,X,FF,98.8,100.2,2483.0,-0.41,6.46,14.0,L,R,2
1,B,FF,98.7,100.0,2522.0,-0.33,6.62,12.0,L,R,1
2,S,SL,89.6,90.8,2537.0,-0.10,6.79,5.0,R,R,6
3,S,FF,100.4,101.7,2469.0,-0.38,6.50,6.0,R,R,5
4,S,FF,97.6,98.9,2339.0,-0.18,6.63,12.0,R,R,4
5,B,FF,98.8,99.9,2372.0,-0.31,6.67,3.0,R,R,3
6,B,FF,99.1,100.4,2502.0,-0.29,6.58,12.0,R,R,2
7,B,SL,89.8,91.0,2345.0,-0.20,6.74,14.0,R,R,1
8,X,SL,86.7,87.9,2419.0,-0.15,6.77,5.0,R,R,3
9,S,SL,86.8,88.1,2459.0,-0.19,6.70,14.0,R,R,2

In [14]:
# Drop columns with NAs 
pitch_df = pitch_df.dropna()

In [13]:
# Export new df as csv file
pitch_df.to_csv('Data/Saved/pitching_2020.csv')